---
name: gdtoolkit3
description: A set of tools for daily work with GDScript for Godot 3.
homepage: https://github.com/Scony/godot-gdscript-toolkit
licenses:
  - MIT
languages:
  - GDScript
categories:
  - Linter
  - Formatter

source:
  id: pkg:pypi/gdtoolkit@3.6.0

bin:
  gdlint: pypi:gdlint
  gdformat: pypi:gdformat
